### ISSUE TITLE
Add cypress and set up GitHub actions with cypress dashboard

### ISSUE THREAD

**Issue by mlodyoskar** [mlodyoskar/Puchacz#2]
Goal of this issue is to set up cypress for automation e2e testing. We want to run test for every deployed environment on vercel. Also we want to see results on cypress dashboard.

- [x] Set up cypress in project
- [x] Write one simple smoke test
- [x] Set up GitHub actions to run every deploy
- [x] Set up cypress dashboard

**Comment by whit33y** [comment]
Cypress and github actions are now working! 🥳
